// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdb.proto

package org.eclipse.imp.pdb.facts.tracking;

import com.google.protobuf.WireFormat;

public final class PDBProtocolBuffers {
  private PDBProtocolBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .BValue.BType type = 1;
    /**
     * <code>optional .BValue.BType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .BValue.BType type = 1;</code>
     */
    org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType getType();

    // optional bytes digest = 2;
    /**
     * <code>optional bytes digest = 2;</code>
     */
    boolean hasDigest();
    /**
     * <code>optional bytes digest = 2;</code>
     */
    org.eclipse.imp.pdb.facts.io.hash.ByteArray getDigest();

    // optional string name = 3;
    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // repeated .BValue nested = 4;
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> 
        getNestedList();
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getNested(int index);
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    int getNestedCount();
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> 
        getNestedOrBuilderList();
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getNestedOrBuilder(
        int index);

    // repeated .BValue.BAnnotation annotations = 5;
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> 
        getAnnotationsList();
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation getAnnotations(int index);
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder> 
        getAnnotationsOrBuilderList();
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder getAnnotationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BValue}
   */
  public static final class BValue extends
      com.google.protobuf.GeneratedMessage
      implements BValueOrBuilder {
    // Use BValue.newBuilder() to construct.
    private BValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BValue defaultInstance;
    public static BValue getDefaultInstance() {
      return defaultInstance;
    }

    public BValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType value = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              digest_ = new org.eclipse.imp.pdb.facts.io.hash.ByteArray(input.readBytes().toByteArray());
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              name_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                nested_ = new java.util.ArrayList<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue>();
                mutable_bitField0_ |= 0x00000008;
              }
              nested_.add(input.readMessage(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.PARSER, extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                annotations_ = new java.util.ArrayList<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation>();
                mutable_bitField0_ |= 0x00000010;
              }
              annotations_.add(input.readMessage(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          nested_ = java.util.Collections.unmodifiableList(nested_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          annotations_ = java.util.Collections.unmodifiableList(annotations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.class, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder.class);
    }

    public static com.google.protobuf.Parser<BValue> PARSER =
        new com.google.protobuf.AbstractParser<BValue>() {
      public BValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BValue> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code BValue.BType}
     */
    public enum BType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BOOL = 1;</code>
       */
      BOOL(0, 1),
      /**
       * <code>INTEGER = 2;</code>
       */
      INTEGER(1, 2),
      /**
       * <code>RATIONAL = 3;</code>
       */
      RATIONAL(2, 3),
      /**
       * <code>REAL = 4;</code>
       */
      REAL(3, 4),
      /**
       * <code>STRING = 5;</code>
       */
      STRING(4, 5),
      /**
       * <code>DATE_TIME = 6;</code>
       */
      DATE_TIME(5, 6),
      /**
       * <code>SOURCE_LOCATION = 7;</code>
       */
      SOURCE_LOCATION(6, 7),
      /**
       * <code>EXTERNAL_VALUE = 8;</code>
       */
      EXTERNAL_VALUE(7, 8),
      /**
       * <code>LIST = 9;</code>
       */
      LIST(8, 9),
      /**
       * <code>MAP = 10;</code>
       */
      MAP(9, 10),
      /**
       * <code>SET = 11;</code>
       */
      SET(10, 11),
      /**
       * <code>NODE = 12;</code>
       */
      NODE(11, 12),
      /**
       * <code>CONSTRUCTOR = 13;</code>
       */
      CONSTRUCTOR(12, 13),
      /**
       * <code>TUPLE = 14;</code>
       */
      TUPLE(13, 14),
      ;

      /**
       * <code>BOOL = 1;</code>
       */
      public static final int BOOL_VALUE = 1;
      /**
       * <code>INTEGER = 2;</code>
       */
      public static final int INTEGER_VALUE = 2;
      /**
       * <code>RATIONAL = 3;</code>
       */
      public static final int RATIONAL_VALUE = 3;
      /**
       * <code>REAL = 4;</code>
       */
      public static final int REAL_VALUE = 4;
      /**
       * <code>STRING = 5;</code>
       */
      public static final int STRING_VALUE = 5;
      /**
       * <code>DATE_TIME = 6;</code>
       */
      public static final int DATE_TIME_VALUE = 6;
      /**
       * <code>SOURCE_LOCATION = 7;</code>
       */
      public static final int SOURCE_LOCATION_VALUE = 7;
      /**
       * <code>EXTERNAL_VALUE = 8;</code>
       */
      public static final int EXTERNAL_VALUE_VALUE = 8;
      /**
       * <code>LIST = 9;</code>
       */
      public static final int LIST_VALUE = 9;
      /**
       * <code>MAP = 10;</code>
       */
      public static final int MAP_VALUE = 10;
      /**
       * <code>SET = 11;</code>
       */
      public static final int SET_VALUE = 11;
      /**
       * <code>NODE = 12;</code>
       */
      public static final int NODE_VALUE = 12;
      /**
       * <code>CONSTRUCTOR = 13;</code>
       */
      public static final int CONSTRUCTOR_VALUE = 13;
      /**
       * <code>TUPLE = 14;</code>
       */
      public static final int TUPLE_VALUE = 14;


      public final int getNumber() { return value; }

      public static BType valueOf(int value) {
        switch (value) {
          case 1: return BOOL;
          case 2: return INTEGER;
          case 3: return RATIONAL;
          case 4: return REAL;
          case 5: return STRING;
          case 6: return DATE_TIME;
          case 7: return SOURCE_LOCATION;
          case 8: return EXTERNAL_VALUE;
          case 9: return LIST;
          case 10: return MAP;
          case 11: return SET;
          case 12: return NODE;
          case 13: return CONSTRUCTOR;
          case 14: return TUPLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<BType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<BType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<BType>() {
              public BType findValueByNumber(int number) {
                return BType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDescriptor().getEnumTypes().get(0);
      }

      private static final BType[] VALUES = values();

      public static BType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private BType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:BValue.BType)
    }

    public interface BAnnotationOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string name = 1;
      /**
       * <code>optional string name = 1;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      // optional .BValue value = 2;
      /**
       * <code>optional .BValue value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional .BValue value = 2;</code>
       */
      org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getValue();
      /**
       * <code>optional .BValue value = 2;</code>
       */
      org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getValueOrBuilder();
    }
    /**
     * Protobuf type {@code BValue.BAnnotation}
     */
    public static final class BAnnotation extends
        com.google.protobuf.GeneratedMessage
        implements BAnnotationOrBuilder {
      // Use BAnnotation.newBuilder() to construct.
      private BAnnotation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private BAnnotation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final BAnnotation defaultInstance;
      public static BAnnotation getDefaultInstance() {
        return defaultInstance;
      }

      public BAnnotation getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private BAnnotation(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = value_.toBuilder();
                }
                value_ = input.readMessage(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(value_);
                  value_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_BAnnotation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_BAnnotation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.class, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder.class);
      }

      public static com.google.protobuf.Parser<BAnnotation> PARSER =
          new com.google.protobuf.AbstractParser<BAnnotation>() {
        public BAnnotation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BAnnotation(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<BAnnotation> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .BValue value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value_;
      /**
       * <code>optional .BValue value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .BValue value = 2;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getValue() {
        return value_;
      }
      /**
       * <code>optional .BValue value = 2;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getValueOrBuilder() {
        return value_;
      }

      private void initFields() {
        name_ = "";
        value_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BValue.BAnnotation}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_BAnnotation_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_BAnnotation_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.class, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder.class);
        }

        // Construct using org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getValueFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (valueBuilder_ == null) {
            value_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance();
          } else {
            valueBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_BAnnotation_descriptor;
        }

        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation getDefaultInstanceForType() {
          return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.getDefaultInstance();
        }

        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation build() {
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation buildPartial() {
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation result = new org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (valueBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = valueBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation) {
            return mergeFrom((org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation other) {
          if (other == org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.getDefaultInstance()) return this;
          if (other.hasName()) {
            bitField0_ |= 0x00000001;
            name_ = other.name_;
            onChanged();
          }
          if (other.hasValue()) {
            mergeValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string name = 1;
        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }

        // optional .BValue value = 2;
        private org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> valueBuilder_;
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getValue() {
          if (valueBuilder_ == null) {
            return value_;
          } else {
            return valueBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public Builder setValue(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value) {
          if (valueBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            value_ = value;
            onChanged();
          } else {
            valueBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public Builder setValue(
            org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder builderForValue) {
          if (valueBuilder_ == null) {
            value_ = builderForValue.build();
            onChanged();
          } else {
            valueBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public Builder mergeValue(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value) {
          if (valueBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                value_ != org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance()) {
              value_ =
                org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.newBuilder(value_).mergeFrom(value).buildPartial();
            } else {
              value_ = value;
            }
            onChanged();
          } else {
            valueBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public Builder clearValue() {
          if (valueBuilder_ == null) {
            value_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance();
            onChanged();
          } else {
            valueBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder getValueBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getValueFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getValueOrBuilder() {
          if (valueBuilder_ != null) {
            return valueBuilder_.getMessageOrBuilder();
          } else {
            return value_;
          }
        }
        /**
         * <code>optional .BValue value = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> 
            getValueFieldBuilder() {
          if (valueBuilder_ == null) {
            valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder>(
                    value_,
                    getParentForChildren(),
                    isClean());
            value_ = null;
          }
          return valueBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:BValue.BAnnotation)
      }

      static {
        defaultInstance = new BAnnotation(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:BValue.BAnnotation)
    }

    private int bitField0_;
    // optional .BValue.BType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType type_;
    /**
     * <code>optional .BValue.BType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .BValue.BType type = 1;</code>
     */
    public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType getType() {
      return type_;
    }

    // optional bytes digest = 2;
    public static final int DIGEST_FIELD_NUMBER = 2;
    private org.eclipse.imp.pdb.facts.io.hash.ByteArray digest_;
    /**
     * <code>optional bytes digest = 2;</code>
     */
    public boolean hasDigest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes digest = 2;</code>
     */
    public org.eclipse.imp.pdb.facts.io.hash.ByteArray getDigest() {
      return digest_;
    }

    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .BValue nested = 4;
    public static final int NESTED_FIELD_NUMBER = 4;
    private java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> nested_;
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> getNestedList() {
      return nested_;
    }
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    public java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> 
        getNestedOrBuilderList() {
      return nested_;
    }
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    public int getNestedCount() {
      return nested_.size();
    }
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getNested(int index) {
      return nested_.get(index);
    }
    /**
     * <code>repeated .BValue nested = 4;</code>
     */
    public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getNestedOrBuilder(
        int index) {
      return nested_.get(index);
    }

    // repeated .BValue.BAnnotation annotations = 5;
    public static final int ANNOTATIONS_FIELD_NUMBER = 5;
    private java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> annotations_;
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> getAnnotationsList() {
      return annotations_;
    }
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    public java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder> 
        getAnnotationsOrBuilderList() {
      return annotations_;
    }
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    public int getAnnotationsCount() {
      return annotations_.size();
    }
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation getAnnotations(int index) {
      return annotations_.get(index);
    }
    /**
     * <code>repeated .BValue.BAnnotation annotations = 5;</code>
     */
    public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder getAnnotationsOrBuilder(
        int index) {
      return annotations_.get(index);
    }

    private void initFields() {
      type_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType.BOOL;
      digest_ = org.eclipse.imp.pdb.facts.io.hash.ByteArray.EMPTY;
      name_ = "";
      nested_ = java.util.Collections.emptyList();
      annotations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeTag(2, WireFormat.WIRETYPE_LENGTH_DELIMITED);
        output.writeRawVarint32(digest_.getBytes().length);
        output.writeRawBytes(digest_.getBytes());   
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      for (int i = 0; i < nested_.size(); i++) {
        output.writeMessage(4, nested_.get(i));
      }
      for (int i = 0; i < annotations_.size(); i++) {
        output.writeMessage(5, annotations_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream.computeTagSize(2) 
        		+ com.google.protobuf.CodedOutputStream.computeRawVarint32Size(digest_.getBytes().length) 
        		+ digest_.getBytes().length;
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      for (int i = 0; i < nested_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, nested_.get(i));
      }
      for (int i = 0; i < annotations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, annotations_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.class, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder.class);
      }

      // Construct using org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNestedFieldBuilder();
          getAnnotationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType.BOOL;
        bitField0_ = (bitField0_ & ~0x00000001);
        digest_ = org.eclipse.imp.pdb.facts.io.hash.ByteArray.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (nestedBuilder_ == null) {
          nested_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          nestedBuilder_.clear();
        }
        if (annotationsBuilder_ == null) {
          annotations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          annotationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.internal_static_BValue_descriptor;
      }

      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getDefaultInstanceForType() {
        return org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance();
      }

      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue build() {
        org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue buildPartial() {
        org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue result = new org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.digest_ = digest_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (nestedBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            nested_ = java.util.Collections.unmodifiableList(nested_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.nested_ = nested_;
        } else {
          result.nested_ = nestedBuilder_.build();
        }
        if (annotationsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            annotations_ = java.util.Collections.unmodifiableList(annotations_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.annotations_ = annotations_;
        } else {
          result.annotations_ = annotationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue) {
          return mergeFrom((org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue other) {
        if (other == org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDigest()) {
          setDigest(other.getDigest());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (nestedBuilder_ == null) {
          if (!other.nested_.isEmpty()) {
            if (nested_.isEmpty()) {
              nested_ = other.nested_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureNestedIsMutable();
              nested_.addAll(other.nested_);
            }
            onChanged();
          }
        } else {
          if (!other.nested_.isEmpty()) {
            if (nestedBuilder_.isEmpty()) {
              nestedBuilder_.dispose();
              nestedBuilder_ = null;
              nested_ = other.nested_;
              bitField0_ = (bitField0_ & ~0x00000008);
              nestedBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNestedFieldBuilder() : null;
            } else {
              nestedBuilder_.addAllMessages(other.nested_);
            }
          }
        }
        if (annotationsBuilder_ == null) {
          if (!other.annotations_.isEmpty()) {
            if (annotations_.isEmpty()) {
              annotations_ = other.annotations_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureAnnotationsIsMutable();
              annotations_.addAll(other.annotations_);
            }
            onChanged();
          }
        } else {
          if (!other.annotations_.isEmpty()) {
            if (annotationsBuilder_.isEmpty()) {
              annotationsBuilder_.dispose();
              annotationsBuilder_ = null;
              annotations_ = other.annotations_;
              bitField0_ = (bitField0_ & ~0x00000010);
              annotationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAnnotationsFieldBuilder() : null;
            } else {
              annotationsBuilder_.addAllMessages(other.annotations_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .BValue.BType type = 1;
      private org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType type_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType.BOOL;
      /**
       * <code>optional .BValue.BType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .BValue.BType type = 1;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType getType() {
        return type_;
      }
      /**
       * <code>optional .BValue.BType type = 1;</code>
       */
      public Builder setType(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .BValue.BType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BType.BOOL;
        onChanged();
        return this;
      }

      // optional bytes digest = 2;
      private org.eclipse.imp.pdb.facts.io.hash.ByteArray digest_ = org.eclipse.imp.pdb.facts.io.hash.ByteArray.EMPTY;
      /**
       * <code>optional bytes digest = 2;</code>
       */
      public boolean hasDigest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes digest = 2;</code>
       */
      public org.eclipse.imp.pdb.facts.io.hash.ByteArray getDigest() {
        return digest_;
      }
      /**
       * <code>optional bytes digest = 2;</code>
       */
      public Builder setDigest(org.eclipse.imp.pdb.facts.io.hash.ByteArray value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        digest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes digest = 2;</code>
       */
      public Builder clearDigest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        digest_ = getDefaultInstance().getDigest();
        onChanged();
        return this;
      }

      // optional string name = 3;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      // repeated .BValue nested = 4;
      private java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> nested_ =
        java.util.Collections.emptyList();
      private void ensureNestedIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          nested_ = new java.util.ArrayList<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue>(nested_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> nestedBuilder_;

      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> getNestedList() {
        if (nestedBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nested_);
        } else {
          return nestedBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public int getNestedCount() {
        if (nestedBuilder_ == null) {
          return nested_.size();
        } else {
          return nestedBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue getNested(int index) {
        if (nestedBuilder_ == null) {
          return nested_.get(index);
        } else {
          return nestedBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder setNested(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value) {
        if (nestedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedIsMutable();
          nested_.set(index, value);
          onChanged();
        } else {
          nestedBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder setNested(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder builderForValue) {
        if (nestedBuilder_ == null) {
          ensureNestedIsMutable();
          nested_.set(index, builderForValue.build());
          onChanged();
        } else {
          nestedBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder addNested(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value) {
        if (nestedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedIsMutable();
          nested_.add(value);
          onChanged();
        } else {
          nestedBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder addNested(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue value) {
        if (nestedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNestedIsMutable();
          nested_.add(index, value);
          onChanged();
        } else {
          nestedBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder addNested(
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder builderForValue) {
        if (nestedBuilder_ == null) {
          ensureNestedIsMutable();
          nested_.add(builderForValue.build());
          onChanged();
        } else {
          nestedBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder addNested(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder builderForValue) {
        if (nestedBuilder_ == null) {
          ensureNestedIsMutable();
          nested_.add(index, builderForValue.build());
          onChanged();
        } else {
          nestedBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder addAllNested(
          java.lang.Iterable<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue> values) {
        if (nestedBuilder_ == null) {
          ensureNestedIsMutable();
          super.addAll(values, nested_);
          onChanged();
        } else {
          nestedBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder clearNested() {
        if (nestedBuilder_ == null) {
          nested_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          nestedBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public Builder removeNested(int index) {
        if (nestedBuilder_ == null) {
          ensureNestedIsMutable();
          nested_.remove(index);
          onChanged();
        } else {
          nestedBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder getNestedBuilder(
          int index) {
        return getNestedFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder getNestedOrBuilder(
          int index) {
        if (nestedBuilder_ == null) {
          return nested_.get(index);  } else {
          return nestedBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> 
           getNestedOrBuilderList() {
        if (nestedBuilder_ != null) {
          return nestedBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nested_);
        }
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder addNestedBuilder() {
        return getNestedFieldBuilder().addBuilder(
            org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance());
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder addNestedBuilder(
          int index) {
        return getNestedFieldBuilder().addBuilder(
            index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.getDefaultInstance());
      }
      /**
       * <code>repeated .BValue nested = 4;</code>
       */
      public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder> 
           getNestedBuilderList() {
        return getNestedFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder> 
          getNestedFieldBuilder() {
        if (nestedBuilder_ == null) {
          nestedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValueOrBuilder>(
                  nested_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          nested_ = null;
        }
        return nestedBuilder_;
      }

      // repeated .BValue.BAnnotation annotations = 5;
      private java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> annotations_ =
        java.util.Collections.emptyList();
      private void ensureAnnotationsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          annotations_ = new java.util.ArrayList<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation>(annotations_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder> annotationsBuilder_;

      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> getAnnotationsList() {
        if (annotationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(annotations_);
        } else {
          return annotationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public int getAnnotationsCount() {
        if (annotationsBuilder_ == null) {
          return annotations_.size();
        } else {
          return annotationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation getAnnotations(int index) {
        if (annotationsBuilder_ == null) {
          return annotations_.get(index);
        } else {
          return annotationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder setAnnotations(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.set(index, value);
          onChanged();
        } else {
          annotationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder setAnnotations(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.set(index, builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder addAnnotations(org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.add(value);
          onChanged();
        } else {
          annotationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder addAnnotations(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation value) {
        if (annotationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnnotationsIsMutable();
          annotations_.add(index, value);
          onChanged();
        } else {
          annotationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder addAnnotations(
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.add(builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder addAnnotations(
          int index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder builderForValue) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.add(index, builderForValue.build());
          onChanged();
        } else {
          annotationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder addAllAnnotations(
          java.lang.Iterable<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation> values) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          super.addAll(values, annotations_);
          onChanged();
        } else {
          annotationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder clearAnnotations() {
        if (annotationsBuilder_ == null) {
          annotations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          annotationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public Builder removeAnnotations(int index) {
        if (annotationsBuilder_ == null) {
          ensureAnnotationsIsMutable();
          annotations_.remove(index);
          onChanged();
        } else {
          annotationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder getAnnotationsBuilder(
          int index) {
        return getAnnotationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder getAnnotationsOrBuilder(
          int index) {
        if (annotationsBuilder_ == null) {
          return annotations_.get(index);  } else {
          return annotationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public java.util.List<? extends org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder> 
           getAnnotationsOrBuilderList() {
        if (annotationsBuilder_ != null) {
          return annotationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(annotations_);
        }
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder addAnnotationsBuilder() {
        return getAnnotationsFieldBuilder().addBuilder(
            org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.getDefaultInstance());
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder addAnnotationsBuilder(
          int index) {
        return getAnnotationsFieldBuilder().addBuilder(
            index, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.getDefaultInstance());
      }
      /**
       * <code>repeated .BValue.BAnnotation annotations = 5;</code>
       */
      public java.util.List<org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder> 
           getAnnotationsBuilderList() {
        return getAnnotationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder> 
          getAnnotationsFieldBuilder() {
        if (annotationsBuilder_ == null) {
          annotationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotation.Builder, org.eclipse.imp.pdb.facts.tracking.PDBProtocolBuffers.BValue.BAnnotationOrBuilder>(
                  annotations_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          annotations_ = null;
        }
        return annotationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BValue)
    }

    static {
      defaultInstance = new BValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BValue)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BValue_BAnnotation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BValue_BAnnotation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tpdb.proto\"\372\002\n\006BValue\022\033\n\004type\030\001 \001(\0162\r.B" +
      "Value.BType\022\016\n\006digest\030\002 \001(\014\022\014\n\004name\030\003 \001(" +
      "\t\022\027\n\006nested\030\004 \003(\0132\007.BValue\022(\n\013annotation" +
      "s\030\005 \003(\0132\023.BValue.BAnnotation\0323\n\013BAnnotat" +
      "ion\022\014\n\004name\030\001 \001(\t\022\026\n\005value\030\002 \001(\0132\007.BValu" +
      "e\"\274\001\n\005BType\022\010\n\004BOOL\020\001\022\013\n\007INTEGER\020\002\022\014\n\010RA" +
      "TIONAL\020\003\022\010\n\004REAL\020\004\022\n\n\006STRING\020\005\022\r\n\tDATE_T" +
      "IME\020\006\022\023\n\017SOURCE_LOCATION\020\007\022\022\n\016EXTERNAL_V" +
      "ALUE\020\010\022\010\n\004LIST\020\t\022\007\n\003MAP\020\n\022\007\n\003SET\020\013\022\010\n\004NO" +
      "DE\020\014\022\017\n\013CONSTRUCTOR\020\r\022\t\n\005TUPLE\020\016B8\n\"org.",
      "eclipse.imp.pdb.facts.trackingB\022PDBProto" +
      "colBuffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BValue_descriptor,
              new java.lang.String[] { "Type", "Digest", "Name", "Nested", "Annotations", });
          internal_static_BValue_BAnnotation_descriptor =
            internal_static_BValue_descriptor.getNestedTypes().get(0);
          internal_static_BValue_BAnnotation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BValue_BAnnotation_descriptor,
              new java.lang.String[] { "Name", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
